### ISSUE TITLE
[Bug] Unable to build appimage

### ISSUE THREAD

**Issue by amaramrahul** [tw93/Pake#1034]
### Search before asking

- [x] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Pake version

3.2.17

### System version

Debian Trixie

### Node.js version

20.19.2

### Minimal reproduce step

pake  https://read.amazon.com --name Kindle --title Kindle --targets appimage

### What did you expect to see?

Appimage is built successfully.

### What did you see instead?

```
⚠ No favicon found for read.amazon.com. Using default.
✼ No icon provided, using default icon.
✶ Installing package...
✔ Package installed!
✸ Building app...
        Info Looking up installed tauri packages to check mismatched versions...
   Compiling pake v3.1.2 (/usr/local/lib/node_modules/pake-cli/src-tauri)
    Finished `release` profile [optimized] target(s) in 1m 16s
       Built application at: /usr/local/lib/node_modules/pake-cli/src-tauri/target/release/pake
        Info Patching binary "/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/pake" for type appimage
    Bundling kindle_1.0.0_amd64.AppImage (/usr/local/lib/node_modules/pake-cli/src-tauri/target/release/bundle/appimage/kindle_1.0.0_amd64.AppImage)
failed to bundle project: `failed to run linuxdeploy`
       Error failed to bundle project: `failed to run linuxdeploy`
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:219
        throw new Error(`Error occurred while executing command "${command}". Exit code: ${exitCode}. Details: ${errorMessage}`);
              ^

Error: Error occurred while executing command "cd "/usr/local/lib/node_modules/pake-cli" && npm run build -- -c "src-tauri/.pake/tauri.conf.json" --features cli-build". Exit code: 1. Details: Command failed with exit code 1: 'cd "/usr/local/lib/node_modules/pake-cli" && npm run build -- -c "src-tauri/.pake/tauri.conf.json" --features cli-build'


> pake-cli@3.2.17 build
> tauri build -c src-tauri/.pake/tauri.conf.json --features cli-build
    at shellExec (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:219:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LinuxBuilder.buildAndCopy (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:700:9)
    at async LinuxBuilder.build (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:988:17)
    at async Command.<anonymous> (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1535:5)

Node.js v20.19.2
```

### Anything else?

Same issue seen even if I build using the below docker command.
```
docker run --rm -v ~/Downloads/pake-packages:/output ghcr.io/tw93/pake https://read.amazon.com --name Kindle --title Kindle --targets appimage
```

I also tried exporting environment variable NO_STRIP=true as this was suggested as a fix in some forums. But that didn't help as well.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by amaramrahul** [comment]
This issue is also reported in the last comments in #826 and the same fix of using NO_STRIP=true is mentioned in one of the comments but it not clear how to add NO_STRIP=true to linuxdeploy command manually. I executed `export NO_STRIP=true' before running pake command but that didn't help.

**Comment by dominix** [comment]
same problem for me

**Comment by amaramrahul** [comment]
@tw93 how were the appimages in Releases built?

We Debian/Ubuntu linux users are blocked as we cannot build appimages (my preferred method) and we cannot use deb because at most only one deb can be installed (see #947).

**Comment by tw93** [comment]
### Solution for AppImage Build Failure

The issue occurs because your local Debian environment is missing system dependencies that are automatically installed in GitHub Actions.

### Root Cause

GitHub Actions successfully builds AppImage because it installs required system dependencies on Ubuntu (see.github/actions/setup-env/action.yml:106-110). Your local environment lacks these dependencies, causing linuxdeploy to fail.

### Fix

Install the missing system dependencies on your Debian system:

```
  sudo apt update
  sudo apt install -y \
    libdbus-1-dev \
    libsoup-3.0-dev \
    libjavascriptcoregtk-4.1-dev \
    libwebkit2gtk-4.1-dev \
    build-essential \
    curl \
    wget \
    file \
    libxdo-dev \
    libssl-dev \
    libgtk-3-dev \
    libayatana-appindicator3-dev \
    librsvg2-dev \
    libglib2.0-dev \
    pkg-config
```

After installing these dependencies, try building the AppImage again:

```
pake https://read.amazon.com --name kindle --title Kindle --targets appimage
```

### Why This Works

These are the exact same dependencies that GitHub Actions installs for successful Linux builds. The linuxdeploy tool requires these libraries to properly bundle the AppImage with all necessary components.

**Comment by dominix** [comment]
thanks tw93
this should be clearly stated in the readme.md of the project.

**Comment by amaramrahul** [comment]
Thanks @tw93 for getting back on this but installing these packages doesn't seem to make any difference.

1. I installed the above packages. Most of them were already installed, and the missing ones were installed freshly.
2. Upgrade to pake 3.2.18
3. Tried building the appimage with the command you shared, and it didn't work. It gave the same error as earlier.
4. exported NO_STRIP=true and again tried building the appimage. But it again failed with exactly the same error.

Could we please re-open this issue till we find a proper fix?

**Comment by tw93** [comment]
@reporter Thanks for the detailed report and for testing the suggested solutions. We've implemented automatic `NO_STRIP`
  environment variable support in the latest version, which should help with linuxdeploy issues.

  ## Current Status

  Please ensure you're using the latest Pake version 3.4.0. The `NO_STRIP=true` solution has been integrated into our build
  process and should work when you run:

  ```bash
  NO_STRIP=true pake https://example.com --name MyApp --targets appimage

  For detailed documentation on this and other solutions, see:
  https://github.com/tw93/Pake/blob/main/docs/faq.md#linux-appimage-build-fails-with-failed-to-run-linuxdeploy

  Additional Diagnostic Steps

  If you're still encountering issues on Debian Trixie even with Pake 3.4.0, could you please try a few more diagnostic steps:

  1. Check environment variable propagation:
  # Verify the variable is set
  NO_STRIP=true bash -c 'echo $NO_STRIP'

  # Then build
  NO_STRIP=true pake https://example.com --name MyApp --targets appimage --debug
  2. Check linuxdeploy versions:
  which linuxdeploy
  linuxdeploy --version
  3. Try with extra logging:
  NO_STRIP=true NO_STRIP_DEBUG=1 pake https://example.com --name MyApp --targets appimage

  Alternative Solutions

  If NO_STRIP doesn't resolve it, here are some alternatives:

  1. Use DEB format (recommended for Debian):
  pake https://example.com --name MyApp --targets deb
  2. Check if it's a glibc compatibility issue:
    - Debian Trixie uses a newer glibc that may be incompatible with linuxdeploy
    - Consider using a Docker container for builds
  3. Manual linuxdeploy installation:
  # Remove any existing linuxdeploy
  sudo apt remove linuxdeploy appimagetool

  # Install manually
  wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  chmod +x linuxdeploy-x86_64.AppImage
  sudo mv linuxdeploy-x86_64.AppImage /usr/local/bin/linuxdeploy

  Could you please share the complete error output with --debug flag enabled? This will help us identify if it's a stripping
  issue specifically or something else with linuxdeploy on Debian Trixie.

  Also, what's your exact Pake version? (pake --version) If you're not on 3.4.0 yet, please upgrade first.

**Comment by amaramrahul** [comment]
This still doesn't work. Please reopen the bug.

Here are the different scenarios that I tried.

1. Running pake directly on Trixie
```
# NO_STRIP=true NO_STRIP_DEBUG=1 pake  https://read.amazon.com --name Kindle --title Kindle --icon /icons/kindle.png --targets appimage --debug
www.npmjs.com latency is 42 ms
✹ Installing package...
✹ Installing package...

up to date, audited 222 packages in 794ms

89 packages are looking for funding
  run `npm fund` for details

✔ Package installed!
✸ Building app...

> pake-cli@3.4.0 build:debug
> tauri build --debug -c src-tauri/.pake/tauri.conf.json --features cli-build

        Info Looking up installed tauri packages to check mismatched versions...
   Compiling pake v3.1.2 (/usr/local/lib/node_modules/pake-cli/src-tauri)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 19.31s
       Built application at: /usr/local/lib/node_modules/pake-cli/src-tauri/target/debug/pake-kindle
        Info Patching binary "/usr/local/lib/node_modules/pake-cli/src-tauri/target/debug/pake-kindle" for type appimage
    Bundling kindle_1.0.0_amd64.AppImage (/usr/local/lib/node_modules/pake-cli/src-tauri/target/debug/bundle/appimage/kindle_1.0.0_amd64.AppImage)
failed to bundle project: `failed to run linuxdeploy`
       Error failed to bundle project: `failed to run linuxdeploy`
file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:232
        throw new Error(errorMsg);
              ^

Error: Error occurred while executing command "cd "/usr/local/lib/node_modules/pake-cli" && npm run build:debug -- -c "src-tauri/.pake/tauri.conf.json" --features cli-build". Exit code: 1. Details: Command failed with exit code 1: 'cd "/usr/local/lib/node_modules/pake-cli" && npm run build:debug -- -c "src-tauri/.pake/tauri.conf.json" --features cli-build'
    at shellExec (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:232:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async LinuxBuilder.buildAndCopy (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:809:9)
    at async LinuxBuilder.build (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1167:17)
    at async Command.<anonymous> (file:///usr/local/lib/node_modules/pake-cli/dist/cli.js:1809:5)
```
2. Running docker
```
$ docker run --rm -v ~/Applications/pake-packages:/output -v ~/.local/share/icons:/icons ghcr.io/tw93/pake https://read.amazon.com --name Kindle --icon /icons/kindle.png  --title Kindle --targets appimage
- Installing package...

✺ Using pnpm for package management.
✔ Package installed!
- Building app...

✸ Building app...
        Info Looking up installed tauri packages to check mismatched versions...
   Compiling pake v3.1.2 (/pake/src-tauri)
    Finished `release` profile [optimized] target(s) in 39.94s
       Built application at: /pake/src-tauri/target/release/pake-kindle
        Info Patching binary "/pake/src-tauri/target/release/pake-kindle" for type appimage
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/apprun-old/AppRun-x86_64
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/linuxdeploy/linuxdeploy-x86_64.AppImage
 Downloading https://raw.githubusercontent.com/tauri-apps/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
 Downloading https://raw.githubusercontent.com/tauri-apps/linuxdeploy-plugin-gstreamer/master/linuxdeploy-plugin-gstreamer.sh
 Downloading https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
    Bundling kindle_1.0.0_amd64.AppImage (/pake/src-tauri/target/release/bundle/appimage/kindle_1.0.0_amd64.AppImage)
failed to bundle project: `failed to run linuxdeploy`
       Error failed to bundle project: `failed to run linuxdeploy`
file:///pake/dist/cli.js:232
        throw new Error(errorMsg);
              ^

Error: Error occurred while executing command "cd "/pake" && pnpm run build -c "src-tauri/.pake/tauri.conf.json" --features cli-build". Exit code: 1. Details: Command failed with exit code 1: 'cd "/pake" && pnpm run build -c "src-tauri/.pake/tauri.conf.json" --features cli-build'


> pake-cli@3.4.0 build /pake
> tauri build -c src-tauri/.pake/tauri.conf.json --features cli-build

\u2009ELIFECYCLE\u2009 Command failed with exit code 1.
    at shellExec (file:///pake/dist/cli.js:232:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async LinuxBuilder.buildAndCopy (file:///pake/dist/cli.js:809:9)
    at async LinuxBuilder.build (file:///pake/dist/cli.js:1167:17)
    at async Command.<anonymous> (file:///pake/dist/cli.js:1809:5)

Node.js v22.20.0
```
3. Running docker with NO_STRIP=true
```
docker run --rm -v ~/Applications/pake-packages:/output -v ~/.local/share/icons:/icons ghcr.io/tw93/pake env NO_STRIP=true pake https://read.amazon.com --name Kindle --icon /icons/kindle.png  --title Kindle --targets appimage
- Installing package...

✺ Using pnpm for package management.
✔ Package installed!
- Building app...

✸ Building app...
        Info Looking up installed tauri packages to check mismatched versions...
   Compiling pake v3.1.2 (/pake/src-tauri)
    Finished `release` profile [optimized] target(s) in 45.70s
       Built application at: /pake/src-tauri/target/release/pake-kindle
        Info Patching binary "/pake/src-tauri/target/release/pake-kindle" for type appimage
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/apprun-old/AppRun-x86_64
 Downloading https://github.com/tauri-apps/binary-releases/releases/download/linuxdeploy/linuxdeploy-x86_64.AppImage
 Downloading https://raw.githubusercontent.com/tauri-apps/linuxdeploy-plugin-gtk/master/linuxdeploy-plugin-gtk.sh
 Downloading https://raw.githubusercontent.com/tauri-apps/linuxdeploy-plugin-gstreamer/master/linuxdeploy-plugin-gstreamer.sh
 Downloading https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage
    Bundling kindle_1.0.0_amd64.AppImage (/pake/src-tauri/target/release/bundle/appimage/kindle_1.0.0_amd64.AppImage)
failed to bundle project: `failed to run linuxdeploy`
       Error failed to bundle project: `failed to run linuxdeploy`
file:///pake/dist/cli.js:232
        throw new Error(errorMsg);
              ^

Error: Error occurred while executing command "cd "/pake" && pnpm run build -c "src-tauri/.pake/tauri.conf.json" --features cli-build". Exit code: 1. Details: Command failed with exit code 1: 'cd "/pake" && pnpm run build -c "src-tauri/.pake/tauri.conf.json" --features cli-build'


> pake-cli@3.4.0 build /pake
> tauri build -c src-tauri/.pake/tauri.conf.json --features cli-build

\u2009ELIFECYCLE\u2009 Command failed with exit code 1.
    at shellExec (file:///pake/dist/cli.js:232:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async LinuxBuilder.buildAndCopy (file:///pake/dist/cli.js:809:9)
    at async LinuxBuilder.build (file:///pake/dist/cli.js:1167:17)
    at async Command.<anonymous> (file:///pake/dist/cli.js:1809:5)

Node.js v22.20.0
```

I find it very strange that even docker command fails because that is independent of the host.

Anyway, I am now using other webapp packaging system as there were multiple issues that I was facing with pake built packages (maybe most of them are fixed now).

If you fix this bug in the future, kindly test with docker command first. Even if it works with docker, it should be fine. If you want to test on Debian Trixie, you can do this by launching docker container for Debian trixie `docker run -it debian:trixie bash`.

**Comment by tw93** [comment]
@amaramrahul Thank you for pointing it out. I will reopen it and we will work together to solve this problem. Let's see if there are any other solutions. I will continue to look into this issue.

**Comment by tw93** [comment]
@amaramrahul Thank you for your patience. I've identified the
root cause and released fixes in Pake 3.4.1.

Root Cause

Modern Linux distros (Debian Trixie, Arch Linux) use glibc
2.38+, which introduced a new .relr.dyn section. The
linuxdeploy tool bundled in Tauri uses an outdated strip
binary that doesn't recognize this format, causing the build
to fail.

Solution

Upgrade to Pake 3.4.1 and use:

```
# Direct build
NO_STRIP=1 pake https://read.amazon.com --name Kindle
--targets appimage --debug

# Docker
docker run --rm -e NO_STRIP=1 -v ~/output:/output \
  ghcr.io/tw93/pake https://read.amazon.com --name Kindle
--targets appimage --debug
```

Important: Use NO_STRIP=1 (not NO_STRIP=true).

What's Improved

- Full error visibility with --debug flag
- Proactive warnings before build
- Clear error messages with actionable solutions

The --debug flag now provides detailed output to help diagnose
 any remaining issues.

Could you test with the new version and share the results?

---
Alternative: If AppImage continues to be problematic, DEB
format works perfectly on Debian-based systems.

**Comment by amaramrahul** [comment]
I am aware that I can use deb, but it requires root access for installation, which I would like to avoid. Hence, I want to use Appimage.

Docker is still at 3.4.0. So I wasn't able to test 3.4.1. Could you please test it? I have a strong suspicion, though, that it will fail (reasoning below).

I tested building appimage directly on my Debian Trixie machine (unlike the previous instances where I tested on Debian Trixie Docker container), and I am pleased to tell you that it worked. AFAIR, here are the commands that I used to build appImage.
```
$ sudo apt update
$ sudo apt install rustc
$ sudo apt install -y \
  libdbus-1-dev \
  libsoup-3.0-dev \
  libjavascriptcoregtk-4.1-dev \
  libwebkit2gtk-4.1-dev \
  build-essential \
  curl wget file \
  libxdo-dev \
  libssl-dev \
  libgtk-3-dev \
  libayatana-appindicator3-dev \
  librsvg2-dev \
  gnome-video-effects \
  libglib2.0-dev \
  libgirepository1.0-dev \
  pkg-config
$ mkdir pake-cli
$ cd pake-cli
$ npm install pake-cli
$ convert <path-to-application-icon-that-you-want-to-use> -type TrueColorAlpha PNG32:kindle.png && mv -f kindle.png ~/.local/share/icons/ # generate compatible icon (https://v2.tauri.app/develop/icons/#creating-icons-manually)
$ ./node_modules/.bin/pake https://read.amazon.com --name Kindle --icon ~/.local/share/icons/kindle.png --targets appimage
```
As you can see, I am not even setting NO_STRIP=1 above. As a matter of fact, I even installed pake 3.4.0, and the appimage got successfully built without setting any NO_STRIP environment variable. So, now I am suspecting that the failure related to building appimage earlier has got to do something with running the build in docker container and has nothing to do with NO_STRIP environment variable. Maybe some additional configuration has to be passed to the docker container so that it can build the appimage successfully?

Anyway, the big disappointment came when I opened the AppImage, and it was blank. This seems to be the same issue as in #977 .

So, it is up to you whether you want to close this ticket or leave it open, as I am able to build appimage directly on my Debian Trixie system but not using docker container. However, it definitely seems to make sense in reopening #977 as that is a blocker for using Appimages in Linux.

**Comment by amaramrahul** [comment]
Ah. So, I have been able to build appimages using docker as well by passing it the "--privileged" argument. The appimage that gets created has root ownership. So that needs to be changed after creation.
```
$ docker run --rm --privileged -v ~/Applications:/output -v ~/.local/share/icons:/icons ghcr.io/tw93/pake https://read.amazon.com --name Kindle --icon /icons/kindle.png --targets appimage
$ sudo chown $(id -nu): ~/Applications/kindle.AppImage
```
I think it should be fine to now go ahead and close this ticket.

Also, reg #977 , I've observed that while the appImage was showing blank on my older laptop (macbook pro 15 running linux), it opens fine on my newer laptop (Asus Zenbook S16 UM5606).

**Comment by tw93** [comment]
@amaramrahul Thank you so much for the detailed testing and perseverance! 🎉

## Summary

You've identified the **exact root cause** - Docker containers need privileged mode to access `/dev/fuse` for
AppImage builds. This is exactly what we've now documented in the latest updates!

## What's Fixed

The dev branch (soon to be released) now includes the proper Docker command with all necessary flags:

```bash
  docker run --rm --privileged \
  --device /dev/fuse \
  --security-opt apparmor=unconfined \
  -v ~/Applications:/output \
  -v ~/.local/share/icons:/icons \
  ghcr.io/tw93/pake \
  https://read.amazon.com --name Kindle --icon /icons/kindle.png --targets appimage
```

**Comment by amaramrahul** [comment]
Thanks for getting back on this. Couple of observations.
1. I did not have to pass the `--device /dev/fuse`  and `--security-opt apparmor=unconfined` options. Just `--privileged` was sufficient. Not sure if it platform specific.
2. You may want to revert code specific changes that you made to support NO_STRIP. Or maybe just keep it if you see a need for it.

Closing the ticket as I am now able to build using 1. Docker and 2. Directly on my system as a normal user.
